Source: Intercom - Mudança no método de extrair conversas
asaasdev/airbyte pull request #3
Opened 2022-01-21 18:25 UTC by asaas-albertnbr

* Cópia do `source-intercom` para `source-intercom-asaas`

* Mudança do endpoint de extração de conversas de `conversations` para `conversations/search` 

* Método alterado de `GET` para `POST` 

* Implementado o slicing e request_body_json.

* Implementado next_page_token.

* Implementado get_updated_state.

2022-01-21 18:45 UTC, juliano-piovezan requested changes
Além disso, instalar black e flake8, existem alguns pontos a serem corrigidos no código. Priorizar somente o código que foi alterado. Muito provavelmente os códigos originais também possuam problemas apontados pelo flake, porém não é necessário corrigir.

Versões dos pacotes que utilizamos:
* black==21.12b0
* flake8==4.0.1
* wemake-python-styleguide==0.16.0

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/Dockerfile
> +LABEL io.airbyte.version=0.1.6
```suggestion
LABEL io.airbyte.version=0.1.0
```
Acredito que podemos reiniciar a versão, uma vez que seria um "novo" conector.

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/Dockerfile
> +LABEL io.airbyte.name=airbyte/source-intercom
```suggestion
LABEL io.airbyte.name=airbyte/source-intercom-asaas
```
Aqui também existe a necessidade de alterar o nome para diferenciar do oficial do Airbyte.

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/README.md
> +./gradlew :airbyte-integrations:connectors:source-intercom:build
```suggestion
./gradlew :airbyte-integrations:connectors:source-intercom-asaas:build
```

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/README.md
> +docker build . -t airbyte/source-intercom:dev
```suggestion
docker build . -t airbyte/source-intercom-asaas:dev
```

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/README.md
> +./gradlew :airbyte-integrations:connectors:source-intercom:airbyteDocker
```suggestion
./gradlew :airbyte-integrations:connectors:source-intercom-asaas:airbyteDocker
```

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/README.md
> +docker run --rm -v $(pwd)/secrets:/secrets -v $(pwd)/integration_tests:/integration_tests airbyte/source-intercom:dev read --config /secrets/config.json --catalog /integration_tests/configured_catalo
```suggestion
docker run --rm airbyte/source-intercom-asaas:dev spec
docker run --rm -v $(pwd)/secrets:/secrets airbyte/source-intercom-asaas:dev check --config /secrets/config.json
docker run --rm -v $(pwd)/secrets:/secrets airbyte/source-intercom-asaas:dev discover --config /secrets/config.json
docker run --rm -v $(pwd)/secrets:/secrets -v $(pwd)/integration_tests:/integration_tests airbyte/source-intercom-asaas:dev read --config /secrets/config.json --catalog /integration_tests/configured_catalog.json
```

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/README.md
> +./gradlew :airbyte-integrations:connectors:source-intercom:unitTest
```suggestion
./gradlew :airbyte-integrations:connectors:source-intercom-asaas:unitTest
```

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/README.md
> +./gradlew :airbyte-integrations:connectors:source-intercom:integrationTest
```suggestion
./gradlew :airbyte-integrations:connectors:source-intercom-asaas:integrationTest
```

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/acceptance-test-config.yml
> +connector_image: airbyte/source-intercom:dev
```suggestion
connector_image: airbyte/source-intercom-asaas:dev
```

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/setup.py
> +    name="source_intercom",
```suggestion
    name="source_intercom_asaas",
```

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/source_intercom/source.py
> +        query = {
Faltou incluir a tag de tamanho da página. Por padrão o tamanho é limitado em 50, porém o máximo é 150.

```
"pagination": {
    "per_page": 150
}
```

Referência: https://developers.intercom.com/intercom-api-reference/reference/pagination-cursor

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/source_intercom/source.py
> +        api_time_windown_days = 30
```suggestion
        api_time_window_days = 30
```

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/source_intercom/source.py
> +            slice_end_date = slice_start_date.add(days=api_time_windown_days)
```suggestion
            slice_end_date = slice_start_date.add(days=api_time_window_days) 
```

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/source_intercom/source.py
> +        # slice_start_date = pendulum.from_timestamp(slice_start_date)
```suggestion

```
Não deixar código comentado.

2022-01-21 18:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/source_intercom/source.py
> +        return f"/conversations/{stream_slice['id']}"
Esse stream herda de `Conversations`, porém ele considera que o mesmo utilize a estratégia anterior. Com a alteração feita esse stream deixa de funcionar. Como ele não será utilizado agora, o ideal seria incluir aqui um `raise` para evitar que se tente executar ele em produção e gere resultados incorretos.

2022-01-24 16:35 UTC, juliano-piovezan requested changes
Ainda existem warnings do flake na classe `Conversations` que necessitam serem corrigidos.

2022-01-25 16:56 UTC, juliano-piovezan requested changes

2022-01-25 16:56 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/source_intercom/source.py
> +        """  # noqa: RST201,RST301
```suggestion
        """Write the JSON request body to query, sort and paginate results.

        Args:
            stream_state (Mapping[str, Any]): stream state.
            stream_slice (Mapping[str, Any], optional): Stream slice. Defaults to None.
            next_page_token (Mapping[str, Any], optional): Next page token. Defaults to None.

        Returns:
            Optional[Mapping]: request body json
        """
```
Remover os `noqa` e manter na mesma linha deixando o warning de tamanho máximo da linha.

2022-01-25 16:56 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/source_intercom/source.py
> +        ))
```suggestion
        self.logger.info(
            "Pages {0}/{1}".format(
                actual_page,
                total_pages,
            ),
        )
```
Nessas situações, colocar o argumento na próxima linha indentado.

2022-01-25 17:48 UTC, asaas-albertnbr commented
@juliano-piovezan Alterado

2022-01-25 18:03 UTC, juliano-piovezan approved these changes
Ok.

2022-01-25 18:03 UTC, merged