Source Google Ads, end date and textual dates added
asaasdev/airbyte pull request #4
Opened 2022-01-27 18:35 UTC by asaas-albertnbr

- Cópia do source-google-ads para source-google-ads-asaas

- Criado o campo `end_date` para streams incrementais

- Implementado suporte para datas textuais ex: `today`,`yesterday`,`XdaysAgo` nos campos `start_date` e `end_date`

2022-02-01 12:30 UTC, juliano-piovezan requested changes

2022-02-02 19:45 UTC, asaas-albertnbr commented on airbyte-integrations/connectors/source-google-ads-asaas/source_google_ads/source.py
> +    return parsed_date.strftime("%Y-%m-%d")
@juliano-piovezan Alterações Feitas

2022-02-03 12:49 UTC, juliano-piovezan requested changes

2022-02-03 12:49 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-google-ads-asaas/source_google_ads/source.py
> +    def __init__(self, date_str) -> None:
Está sendo construído um objeto para converter somente uma data em específico. Sugiro alterar e receber a data ser transformada como parâmetro da função `transform_date`, podendo assim reutilizar um mesmo objeto para várias datas.

A variável patterns que está na função `convert_textual_date` podem ser inicializados no construtor desse objeto. Sugiro, também, em transformar a função `convert_textual_date` em privada, seguindo o padrão de incluir o `_` no início, ficando `_convert_textual_date`.

2022-02-03 12:49 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-intercom-asaas/setup.cfg
> +[flake8]
Esse arquivo é do intercom, por que está nesse PR?

2022-02-03 13:28 UTC, asaas-albertnbr commented on airbyte-integrations/connectors/source-intercom-asaas/setup.cfg
> +[flake8]
Esse arquivo é o `setup.cfg`, configuração do flake, havia esquecido de acionar no PR do Intercom, portanto adicionei nesse, por ser apenas um arquivo de configuração da extensão, achei tranquilo adicionar no PR, porém se for melhor posso criar outro PR apenas para adicionar esse arquivo

2022-02-03 19:51 UTC, asaas-albertnbr commented
@juliano-piovezan Alterações efetuadas

2022-02-04 13:45 UTC, juliano-piovezan requested changes

2022-02-04 13:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-google-ads-asaas/source_google_ads/source.py
> +        self.handler_func = handler_func
```suggestion
        self._pattern = pattern
        self._handler_func = handler_func
```
Utilizar padrão para variáveis privadas. Necessário alterar onde é referenciado.

2022-02-04 13:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-google-ads-asaas/source_google_ads/source.py
> +    def __init__(self, patterns: list) -> None:
```suggestion
    def __init__(self, patterns: List[PatternHandler]) -> None:
```
Melhorar o typing do `patterns`.

2022-02-04 13:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-google-ads-asaas/source_google_ads/source.py
> +        self.patterns = patterns
```suggestion
        self._patterns = patterns
```
Privado.

2022-02-04 13:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-google-ads-asaas/source_google_ads/source.py
> +    def transform_date(self, date_str: str) -> str:
Essa função não deveria retornar um `datetime`?

2022-02-04 13:45 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-google-ads-asaas/source_google_ads/source.py
> +        return parsed_date.strftime("%Y-%m-%d") if parsed_date else None
Desnecessário o `if` pois se o padrão estiver errado deverá ser lançada a exceção.

2022-02-04 13:53 UTC, juliano-piovezan requested changes

2022-02-04 13:53 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-google-ads-asaas/source_google_ads/source.py
> +    def streams(self, config: Mapping[str, Any]) -> List[Stream]:
Fatorar o a parte do tratamento do pattern em outra função, pois essa função está muito grande.

2022-02-07 14:34 UTC, juliano-piovezan commented
Corrigir o título do PR, o padrão é manter em português.

2022-02-07 16:24 UTC, asaas-albertnbr commented
@juliano-piovezan Corrigido

2022-02-07 17:21 UTC, juliano-piovezan commented
Realizei testes com o conector e encontrei duas inconsistências:

- Período de extração.
- Campanhas faltantes.

### Período de extração

Configurei o conector com os seguintes parâmetros:
![image](https://user-images.githubusercontent.com/82399724/152838169-830865c7-ff33-4eba-a78f-a706040563d3.png)

Porém ele extraiu dados para o seguinte intervalo:
![image](https://user-images.githubusercontent.com/82399724/152838315-25590bb1-a6eb-4401-a55b-1b9c8b8527d4.png)

### Campanhas faltantes
Com a extração realizada anteriormente, comparei as métricas para o dia 2022-01-02 e encontrei diferença nas métricas extraídas:

![image](https://user-images.githubusercontent.com/82399724/152838815-ddba8abf-0945-4189-9ec8-e3270108a89c.png)

Pode ser validado com a seguinte query:

```
WITH new_metrics AS (

    SELECT
        SUM(`metrics.clicks`) AS clicks,
        SUM(`metrics.conversions`) AS conversions,
        SUM(`metrics.engagements`) AS engagements,
        SUM(`metrics.impressions`) AS impressions,
        SUM(`metrics.interactions`) AS interactions
    FROM test_airbyte.campaign_metrics_report
    WHERE `segments.date` = '2022-01-02'

),

old_metrics AS (

    SELECT
        SUM(gads_campaign_performance_report.clicks) AS clicks,
        SUM(gads_campaign_performance_report.conversions) AS conversions,
        SUM(gads_campaign_performance_report.engagements) AS engagements,
        SUM(gads_campaign_performance_report.impressions) AS impressions,
        SUM(gads_campaign_performance_report.interactions) AS interactions
    FROM data_mart_marketing.gads_campaign_performance_report
    INNER JOIN data_mart_marketing.gads_campaigns ON gads_campaigns.id = gads_campaign_performance_report.campaignid
    WHERE day = '2022-01-02'

)

SELECT
    new_metrics.clicks,
    old_metrics.clicks,
    new_metrics.conversions,
    old_metrics.conversions,
    new_metrics.engagements,
    old_metrics.engagements,
    new_metrics.impressions,
    old_metrics.impressions,
    new_metrics.interactions,
    old_metrics.interactions
FROM new_metrics
INNER JOIN old_metrics ON (true);
```

Investigando, notei que o report novo não está trazendo as campanhas cujo `advertisingChannel` é igual a `Multi Channel`:

![image](https://user-images.githubusercontent.com/82399724/152839068-02da09c9-5d57-452f-bbd0-7ce3527619e6.png)

2022-02-09 18:18 UTC, asaas-albertnbr commented
@juliano-piovezan Slices ajustados!

Alterei seu código SQL para verificação de integridade dos dados

```
WITH new_metrics AS (

    SELECT
    	`customer.id` as customer_id, 
        `segments.date` as segments_date ,
        SUM(`metrics.clicks`) AS clicks,
        SUM(`metrics.cost_micros`) AS cost,
        SUM(`metrics.conversions`) AS conversions,
        SUM(`metrics.engagements`) AS engagements,
        SUM(`metrics.impressions`) AS impressions,
        SUM(`metrics.interactions`) AS interactions
    FROM test.gads_campaign_metrics_report
    group by customer_id,segments_date

),

old_metrics AS (

    SELECT 
        `customerID`  as customer_id,
        `day`  as segments_date , 
        SUM(gads_campaign_performance_report.clicks) AS clicks,
        SUM(gads_campaign_performance_report.cost) AS cost,
        SUM(gads_campaign_performance_report.conversions) AS conversions,
        SUM(gads_campaign_performance_report.engagements) AS engagements,
        SUM(gads_campaign_performance_report.impressions) AS impressions,
        SUM(gads_campaign_performance_report.interactions) AS interactions
    FROM data_mart_marketing.gads_campaign_performance_report
   	group by customer_id,segments_date 

)

SELECT
	new_metrics.customer_id,
	new_metrics.segments_date,
        new_metrics.clicks as new_clicks,
        old_metrics.clicks as old_clicks,
	new_metrics.cost  as new_cost,
	old_metrics.cost  as old_cost,
	new_metrics.conversions  as new_conversions,
	old_metrics.conversions  as old_conversions,
	new_metrics.engagements  as new_engagements,
	old_metrics.engagements  as old_engagements,
	new_metrics.impressions  as new_impressions,
	old_metrics.impressions  as old_impressions,
	new_metrics.interactions  as new_interactions,
	old_metrics.interactions  as old_interactions,
	case when new_metrics.clicks-old_metrics.clicks != 0 then "NOK" else "OK" end as click_check,
	case when (new_metrics.cost/1000000)-old_metrics.cost != 0 then "NOK" else "OK" end as cost_check,
	case when ABS(new_metrics.conversions-old_metrics.conversions) > 0.1 then "NOK" else "OK" end as conversions_check,
	case when new_metrics.engagements-old_metrics.engagements != 0 then "NOK" else "OK" end as engagements_check,
	case when new_metrics.impressions-old_metrics.impressions != 0 then "NOK" else "OK" end as impressions_check,
	case when new_metrics.interactions-old_metrics.interactions != 0 then "NOK" else "OK" end as interactions_check
FROM new_metrics
INNER JOIN old_metrics 
ON new_metrics.customer_id = old_metrics.customer_id
and new_metrics.segments_date = old_metrics.segments_date
order by new_metrics.segments_date;
```

2022-02-11 18:11 UTC, juliano-piovezan commented
Realizei testes com os intervalos de datas e encontrei um problema no caso de uso de extração dos dados do dia atual, onde `start_date=[data início operação]` e `end_date=null`. Na primeira extração não há problema. Nas extrações seguintes, onde o Airbyte terá carregado o `state` salvo da extração inicial, o conector está somando um dia ao `start_date` e um dia ao `end_date`.

Segue exemplo do `config.json` e `state.json` utilizados:

`config.json`
```
{
  "start_date": "2021-06-10",
  "customer_id": "6448962031",
  "credentials": {
    "refresh_token": "",
    "developer_token": "",
    "client_id": "",
    "client_secret": ""
  },
  "conversion_window_days": 0
}
```

`state.json`
```
{"campaign_metrics_report": {"segments.date": "2022-02-11"}}
```

2022-02-14 12:35 UTC, juliano-piovezan approved these changes

2022-02-14 12:35 UTC, merged