Source Banco Central: Criação
asaasdev/airbyte pull request #8
Opened 2022-03-10 13:43 UTC by asaas-albertnbr

* Fonte de dados Banco Central criado

* Streaming do histórico da taxa SELIC implementado

2022-03-14 18:15 UTC, asaas-albertnbr commented
@juliano-piovezan Feito!

2022-03-16 16:05 UTC, juliano-piovezan requested changes

2022-03-16 16:05 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-brazil-central-bank/source_brazil_central_bank/source.py
> +    """
```suggestion
    """Stream Interest Rate (Taxa SELIC)."""
```

2022-03-16 16:05 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-brazil-central-bank/source_brazil_central_bank/source.py
> +            next_page_token (Mapping[str, Any], optional): _description_. Defaults to None.
Sempre preencher a descrição do arg.

2022-03-16 16:05 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-brazil-central-bank/source_brazil_central_bank/source.py
> +    """
```suggestion
    """Source Brazil Central Bank."""
```

2022-03-17 13:06 UTC, asaas-albertnbr commented
@juliano-piovezan Padrões ajustados

2022-03-17 18:44 UTC, juliano-piovezan approved these changes

2022-03-17 18:44 UTC, merged