Source Pontomais: Criação
asaasdev/airbyte pull request #9
Opened 2022-06-17 19:25 UTC by asaas-albertnbr

* Fonte de dados Pontomais criado

* Streaming `Employee` criado

2022-06-17 19:42 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-pontomais/setup.cfg
> +quotes = "
```suggestion
quotes = "

```

2022-06-17 19:42 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-pontomais/source_pontomais/source.py
> +        date = datetime.today().strftime("%Y-%m-%d")
Acredito que esteja faltando controle da janela de extração. Dessa forma como está implementado não seria possível realizar um backfill de dados passados.

2022-06-17 19:54 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-pontomais/source_pontomais/source.py
> +        yield {"data": csv_data}
Caso o relatório não seja gerado dentro das 100 iterações, será retornado nulo no campo `data`. O correto é lançar uma exceção.

Já existem implementações prontas, também, de rate limit e backoff. Dar uma olhada em https://github.com/airbytehq/airbyte/blob/acd1533cecb280821ed381f2756c9ee0ee600525/airbyte-cdk/python/airbyte_cdk/sources/streams/http/rate_limiting.py e https://github.com/asaasdev/data-science-embulk/blob/ef55b8eebbccd5adf8505a2cda01ed4f1e86248d/automation/common/clients/airbyte/client.py#L136

2022-06-17 19:55 UTC, asaas-albertnbr commented on airbyte-integrations/connectors/source-pontomais/source_pontomais/source.py
> +        date = datetime.today().strftime("%Y-%m-%d")
@juliano-piovezan essa data na verdade não faz diferença pra extração, pois sempre busca os resultados atuais, com a opção `with_inactives`, trará também os funcionários que já não estão mais ativos.

2022-06-17 20:01 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-pontomais/source_pontomais/source.py
> +        date = datetime.today().strftime("%Y-%m-%d")
Como é um problema do source, então pode ignorar. Só acrescentar a informação no docstring de que o comportamento é causado por uma limitação da API.

2022-06-17 20:39 UTC, asaas-albertnbr commented on airbyte-integrations/connectors/source-pontomais/source_pontomais/source.py
> +        date = datetime.today().strftime("%Y-%m-%d")
@juliano-piovezan Feito

2022-06-20 19:57 UTC, asaas-albertnbr commented
@juliano-piovezan Ajustes Realizados

2022-06-28 17:10 UTC, juliano-piovezan requested changes

2022-06-30 17:11 UTC, asaas-albertnbr commented
@juliano-piovezan Sugestões aplicadas

2022-06-30 17:22 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-pontomais/source_pontomais/pontomais.py
> +        user_agent: str = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",  # noqa: E501
Ele não preenche o content-type correto porque no metódo request_body_data está sendo retornando uma string, gerada pelo json.dumps. Se retornar o dicionário direto ele irá tratar o tipo de forma correta tornando essa classe desnecessária.

2022-06-30 19:23 UTC, juliano-piovezan requested changes

2022-06-30 19:23 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-pontomais/source_pontomais/pontomais.py
> +    def login(self, config: Mapping[str, str]) -> PontomaisLoginResponse:
Evitar utilizar dicionários genéricos como parâmetros para métodos. Neste caso se conhece com antecedência os atributos de autenticação, no caso login e senha.

Duas opções:
- Separar em dois parâmetros `login(self, login: str, password: str)`
- Criar uma classe `PontomaisCredentials` com os atributos `login` e `password` e declarar `login(self, credentials: PontomaisCredentials)`

2022-06-30 19:23 UTC, juliano-piovezan commented on airbyte-integrations/connectors/source-pontomais/source_pontomais/source.py
> +        return json.dumps(
Retornar o dicionário em vez de string.

2022-07-01 17:03 UTC, asaas-albertnbr commented on airbyte-integrations/connectors/source-pontomais/source_pontomais/pontomais.py
> +        user_agent: str = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",  # noqa: E501
@juliano-piovezan está certo, método alterado e classe removida

2022-07-01 20:16 UTC, juliano-piovezan approved these changes

2022-07-01 20:17 UTC, merged